version: '3.8'

services:
  orderbook:
    build:
      context: .
      dockerfile: atra-ob/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - BIND_ADDRESS=0.0.0.0:50051
    networks:
      - atra-net
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  atra-net:
    driver: bridge
    name: atra
