services:
  matcher:
    build:
      context: .
      dockerfile: atra-ob/Dockerfile
      tags:
        - "atra/matcher:${IMAGE_TAG:-latest}"
        - "atra/matcher:${GIT_COMMIT_SHA:-temp}"
        - "atra/matcher:latest" # for now.
    image: "atra/matcher:${IMAGE_TAG:-latest}"
    ports:
      - "50051:50051"
    environment:
      - BIND_ADDRESS=0.0.0.0:50051
    networks:
      - atra-net
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
      tags:
        - "atra/cli:${IMAGE_TAG:-latest}"
        - "atra/cli:${GIT_COMMIT_SHA:-temp}"
        - "atra/cli:latest" # for now.
    image: "atra/cli:${IMAGE_TAG:-latest}"
    networks:
      - atra-net
    depends_on:
      matcher:
        condition: service_healthy

networks:
  atra-net:
    driver: bridge
    name: atra
