services:
  matcher:
    build:
      context: .
      dockerfile: atra-ob/Dockerfile
      tags:
        - "atra/matcher:${IMAGE_TAG:-latest}"
        - "atra/matcher:${GIT_COMMIT_SHA:-temp}"
        - "atra/matcher:latest" # for now.
    image: "atra/matcher:${IMAGE_TAG:-latest}"
    ports:
      - "50051:50051"
    environment:
      - BIND_ADDRESS=0.0.0.0:50051
    networks:
      - atra-net
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  gateway:
    build:
      context: .
      dockerfile: atra-gateway/Dockerfile
      tags:
        - "atra/gateway:${IMAGE_TAG:-latest}"
        - "atra/gateway:${GIT_COMMIT_SHA}"
        - "atra/gateway:latest"
    image: "atra/gateway:${IMAGE_TAG:-latest}"
    ports:
      - "50052:50052"
    environment:
      - MATCHER_HOST=matcher
      - MATCHER_PORT=50051
      - GATEWAY_PORT=50052
    networks:
      - atra-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50052"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s
  
  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
      tags:
        - "atra/cli:${IMAGE_TAG:-latest}"
        - "atra/cli:${GIT_COMMIT_SHA:-temp}"
        - "atra/cli:latest" # for now.
    image: "atra/cli:${IMAGE_TAG:-latest}"
    environment:
      - atra_OB_HOST=gateway
      - atra_OB_PORT=50052 
    networks:
      - atra-net

networks:
  atra-net:
    driver: bridge
    name: atra
