apiVersion: v1
kind: Service
metadata:
  name: matcher
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: matcher
  ports:
  - port: {{ .Values.matcher.port }}
    targetPort: {{ .Values.matcher.port }}
  type: ClusterIP
