apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: atra

spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: willvchandler/atra-gateway:latest
        ports:
        - containerPort: 50052
        env:
        - name: MATCHER_HOST
          value: "matcher"
        - name: MATCHER_PORT
          value: "50051"
        - name: GATEWAY_PORT
          value: "50052"
        readinessProbe:
          exec:
            command: ["nc", "-z", "localhost", "50052"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["nc", "-z", "localhost", "50052"]
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
