[package]
name = "kobara-ob"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = "1.32"
rust_decimal_macros = "1.32"

[dev-dependencies]
assert_matches = "1.5"
