---
# Source: atra/templates/namespace.yaml.bak
apiVersion: v1
kind: Namespace
metadata:
  name: atra
---
# Source: atra/templates/gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: atra
spec:
  selector:
    app: gateway
  ports:
  - port: 50052
    targetPort: 50052
  type: ClusterIP
---
# Source: atra/templates/matcher-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: matcher
  namespace: atra
spec:
  selector:
    app: matcher
  ports:
  - port: 50051
    targetPort: 50051
  type: ClusterIP
---
# Source: atra/templates/gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: atra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: willvchandler/atra-gateway:latest
        ports:
        - containerPort: 50052
        env:
        - name: MATCHER_HOST
          value: "matcher"
        - name: MATCHER_PORT
          value: "50051"
        - name: GATEWAY_PORT
          value: "50052"
---
# Source: atra/templates/matcher-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcher
  namespace: atra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matcher
  template:
    metadata:
      labels:
        app: matcher
    spec:
      containers:
      - name: matcher
        image: willvchandler/atra-matcher:latest
        ports:
        - containerPort: 50051
        env:
        - name: BIND_ADDRESS
          value: "0.0.0.0:50051"
