name: Prep

on: [push]
  # workflow_call:
  #   inputs:
  #     proto-artifact:
  #       required: true
  #       type: string
  #     rust-artifact:
  #       required: true
  #       type: string

jobs:
  prep-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Prepare Environment, Build, and Upload Artifacts
        id: prepare_step 
        uses: ./.github/actions/prepare-env

      - name: Show artifact names
        run: |
          echo "Proto artifact was uploaded as: ${{ steps.prepare_step.outputs.uploaded-proto-artifact-name }}"
          echo "Rust artifact was uploaded as: ${{ steps.prepare_step.outputs.uploaded-rust-artifact-name }}"
      
      # - uses: actions/checkout@v4
      
      # - name: Download proto artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: ${{ inputs.proto-artifact }}
      #     path: proto-temp
      
      # - name: Download Rust build artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: ${{ inputs.rust-artifact }}
      #     path: atra-ob/target
      
      # - name: Install Rust
      #   uses: dtolnay/rust-toolchain@stable
      
      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'
      #     cache: 'pip'
        
      # - name: Install Python test dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install pytest
      #     cd cli
      #     pip install -r requirements.txt
      
      # - name: Run Rust tests
      #   run: cd atra-ob && cargo test --verbose
      
      # - name: Copy generated protobuf
      #   run: |
      #     mkdir -p cli/src/atra_cli_core/generated
      #     cp -r proto-temp/* cli/src/atra_cli_core/generated/
      
      # - name: Run Python tests
      #   run: |
      #     cd cli
      #     python -m pytest tests/ -v
